openapi: 3.0.0
info:
  title: Mock Target API
  description: A simple mock API for testing purposes.
  version: 1.0.0
servers:
  - url: https://mocktarget.apigee.net
paths:
  /:
    get:
      summary: Get a greeting message
      parameters:
        - in: query
          name: user
          schema:
            type: string
          description: Name of the user to greet
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
